spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
