server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: clients
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/clients/**, /api/v1/goals/**, /api/v1/measurements/**
        - id: plans
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/plans/**
        - id: class
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/classes/**
        - id: class
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/admins/**, /api/v1/companies/**
        - id: class
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/trainers/**
eureka:
  client:
    register-with-eureka: false
