spring:
  config:
    import: optional:configserver:http://config-service:8888
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-service
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://eureka-service:${server.port}/eureka/
